function(ADD_CATCH2_DEPENDENCY DOWNLOAD_PREFIX GIT_VERSION TARGET_NAME SCOPE CATCH_TARGET CXX_STANDARD)
	find_package(Catch2 3 REQUIRED)

	target_link_libraries(${TARGET_NAME} PRIVATE ${CATCH_TARGET})
	add_dependencies(${TARGET_NAME} ${CATCH_TARGET})

endfunction()